#!/usr/bin/env python3
"""Generate ngspice ESD decks (HBM / MM / CDM) for MIPI_IOPadIOVss / MIPI_IOPadIOVdd.
Cells are XOR-identical to sg13g2_IOPadIOVss / sg13g2_IOPadIOVdd -> IHP netlist used.
Corner: mos_tt / res_typ / dio_tt, 25 C, unpowered (all supplies floating, JS-001 style:
only the zapped pin and the reference pin are connected; others floating, 1 GOhm leak).
Usage: gen_decks.py <pdk_root/pdk> <bench_dir>
"""
import sys, os
PDK, BENCH = sys.argv[1], os.path.abspath(sys.argv[2])
M = PDK + '/libs.tech/ngspice/models'
O = PDK + '/libs.tech/ngspice/osdi'
DECKS = os.path.join(BENCH, 'decks'); os.makedirs(DECKS, exist_ok=True)

# stress models ------------------------------------------------------------
# HBM : ANSI/ESDA/JEDEC JS-001 : 100 pF / 1500 Ohm (+2.5 uH series L to get tr 2-10 ns;
#       short-circuit check : Ip = 0.640 A/kV, tr(10-90) = 3.8 ns, decay 151 ns)
# MM  : JESD22-A115 / ESDA STM5.2 (withdrawn, legacy) : 200 pF / 0 Ohm, 0.75 uH series L
#       (+1 Ohm numerical/contact damping); short : Ip = 3.2 A @ 200 V, ring 13 MHz
# CDM : ANSI/ESDA/JEDEC JS-002, simplified : device body (substrate sub!) charged to V
#       through C = 6.8 pF (small verification module) against the field plate (node 0);
#       level > 0 : V(sub!) - V(plate) = +level at t=0+ (device charged positive,
#       current flows OUT of the zapped pin).
#       pogo pin = 5 nH + 70 Ohm (arc + probe) from the zapped pin to the plate.
# A charged capacitor is modelled as an uncharged capacitor in series with a 10 ps
# voltage step (Thevenin equivalent) -> consistent DC operating point, no 'uic'.
#       short : Ip = 5.7 A @ 500 V, FWHM 0.54 ns.
STRESS = {
 'HBM': dict(levels=[1000,2000,3000,4000,6000,8000], tran='tran 0.05n 400n 0 0.5n',
   src=lambda zap, ref: f"Vstep hv 0 PWL(0 0 10p {{vz}})\nCs hv c1 100p\nLs c1 n1 2.5u\nRs n1 {zap} 1500\nVref {ref} 0 0\n"),
 'MM':  dict(levels=[200], tran='tran 0.02n 250n 0 0.2n',
   src=lambda zap, ref: f"Vstep hv 0 PWL(0 0 10p {{vz}})\nCs hv c1 200p\nLs c1 n1 0.75u\nRs n1 {zap} 1\nVref {ref} 0 0\n"),
 'CDM': dict(levels=[250,500,1000], tran='tran 1p 3n 0 5p',
   src=lambda zap, ref: f"Cs sub! c1 6.8p\nVstep c1 0 PWL(0 0 10p {{vz}})\nLs {zap} n1 5n\nRs n1 0 70\n"),
}
CELLS = {'IOVss': ('xiovss', 'sg13g2_IOPadIOVss', 'iovss', ['iovdd', 'vss', 'vdd']),
         'IOVdd': ('xiovdd', 'sg13g2_IOPadIOVdd', 'iovdd', ['iovss', 'vss', 'vdd'])}
RING = [('xvdd', 'sg13g2_IOPadVdd'), ('xvss', 'sg13g2_IOPadVss'),
        ('xiovdd', 'sg13g2_IOPadIOVdd'), ('xiovss', 'sg13g2_IOPadIOVss')]
PROBES = {'xiovdd': [('Icl_io', 'v.xiovdd.xi1.vsc')],
          'xvdd':   [('Icl_core', 'v.xvdd.xi1.vsc')],
          'xiovss': [('Idcp_iovss', 'v.xiovss.xi2.vsp'), ('Idcn_iovss', 'v.xiovss.xi3.vsn')],
          'xvss':   [('Idcn_vss', 'v.xvss.xi1.vsn'), ('Idcp_vss', 'v.xvss.xi2.vsp')]}

OPTS = '.options reltol=1e-3 abstol=1e-9 vntol=1e-5 itl4=200'
def deck(cell, ctx, var, st, ref, pol, levels=None, opts=OPTS, suffix=''):
    inst, sub, pad, _ = CELLS[cell]
    insts = [(inst, sub)] if ctx == 'seul' else RING
    s = STRESS[st]
    lv = [pol * l for l in (levels or s['levels'])]
    name = f"{cell}_{ctx}_{var}_{st}_{'P' if pol > 0 else 'N'}{'_vs_' + ref if ref else ''}{suffix}"
    t = [f"* ESD bench {name} : {st} {'+' if pol>0 else '-'} on {pad}" + (f" vs {ref}" if ref else " (CDM, charge on sub!)"),
         "* generated by gen_decks.py -- corner tt/typ, 25 C, unpowered (supplies floating)",
         ".param vz=1",
         f".lib {M}/cornerMOShv.lib mos_tt", f".lib {M}/cornerMOSlv.lib mos_tt",
         f".lib {M}/cornerRES.lib res_typ", f".lib {M}/cornerDIO.lib dio_tt",
         f".include {BENCH}/io_probe_{var}.spice", ".global sub!", ".temp 25",
         opts]
    for i, sc in insts:
        t.append(f"{i} vdd vss iovdd iovss {sc}")
    for n in ('vdd', 'vss', 'iovdd', 'iovss', 'sub!'):
        if n != ref: t.append(f"Rleak_{n.strip('!')} {n} 0 1G")
    t.append(s['src'](pad, ref).rstrip())
    probes = [p for i, _ in insts for p in PROBES[i]]
    t += [".control", f"pre_osdi {O}/psp103.osdi", f"pre_osdi {O}/r3_cmc.osdi",
          f"foreach lvl {' '.join(map(str, lv))}", "  alterparam vz=$lvl", "  reset", "  " + s['tran'],
          f"  let vpair = vecmax(abs(v({pad})-v({ref or 'P'})))" if ref else "  let vpair = vecmax(abs(v(iovss)-v(sub!)))",
          "  let vio = vecmax(abs(v(iovdd)-v(iovss)))",
          "  let vgnd = vecmax(abs(v(iovss)-v(vss)))",
          "  let viovss = vecmax(abs(v(iovdd)-v(vss)))",
          "  let izap = vecmax(abs(i(Ls)))",
          "  let tend = time[length(time)-1]"]
    extra = []
    if ctx == 'ring':   # vdd is not connected inside a single IO cell -> only meaningful in ring
        t += ["  let vcore = vecmax(abs(v(vdd)-v(vss)))",
              "  let viovdd = vecmax(abs(v(iovdd)-v(vdd)))",
              "  let vissvdd = vecmax(abs(v(iovss)-v(vdd)))"]
        extra = ['vcore', 'viovdd', 'vissvdd']
    for k, v in probes:
        t.append(f"  let {k} = vecmax(abs({v}#branch))")
    keys = ['tend', 'vpair', 'vio', 'vgnd', 'viovss'] + extra + ['izap'] + [k for k, _ in probes]
    t.append(f"  echo RES {cell} {ctx} {var} {st} {pad} {ref or 'CDM'} $lvl " + ' '.join(f"{k}=$&{k}" for k in keys))
    t += ["end", "quit", ".endc", ".end"]
    open(os.path.join(DECKS, name + '.spice'), 'w').write('\n'.join(t) + '\n')
    return name

names = []
# 'esd' variant (ESD diode models) = reference results; 'pdk' variant (antenna-diode
# models as netlisted) only as a model-validity check, standalone, HBM 2 kV.
for cell, (_, _, pad, refs) in CELLS.items():
    for ctx in ('seul', 'ring'):
        for pol in (1, -1):
            for st in ('HBM', 'MM'):
                for ref in refs:
                    if ctx == 'seul' and ref == 'vdd':
                        continue   # vdd not connected inside the cell (no path) -> N/A
                    names.append(deck(cell, ctx, 'esd', st, ref, pol))
                    if ctx == 'seul' and st == 'HBM':
                        names.append(deck(cell, ctx, 'pdk', st, ref, pol, levels=[2000]))
            names.append(deck(cell, ctx, 'esd', 'CDM', None, pol))
open(os.path.join(DECKS, 'LIST'), 'w').write('\n'.join(names) + '\n')
# second pass : fine HBM sweep on the clamp pair, and retries (gear, looser tolerances) of
# runs that stopped on 'timestep too small' before the stress peak.
GEAR = '.options method=gear reltol=2e-3 abstol=1e-6 vntol=1e-4 itl4=500'
extra = [deck('IOVdd', 'seul', 'esd', 'HBM', 'iovss', 1, levels=[2000, 2100, 2200, 2300, 2400, 2600, 2800], suffix='_fine'),
         deck('IOVdd', 'ring', 'esd', 'HBM', 'iovss', 1, levels=[2200, 2400], suffix='_fine')]
# below-grid points for the ring combos that already fail at 1 kV (core rail vdd)
for cell, pol in [('IOVss', -1), ('IOVdd', 1), ('IOVdd', -1)]:
    extra.append(deck(cell, 'ring', 'esd', 'HBM', 'vdd', pol, levels=[500, 750], suffix='_low'))
for cell, ctx, st, ref, pol in [('IOVdd', 'seul', 'CDM', None, 1), ('IOVdd', 'seul', 'MM', 'iovss', -1),
                                ('IOVdd', 'seul', 'MM', 'vss', 1), ('IOVdd', 'seul', 'MM', 'vss', -1),
                                ('IOVdd', 'seul', 'HBM', 'iovss', -1), ('IOVdd', 'ring', 'MM', 'vdd', 1),
                                ('IOVdd', 'ring', 'MM', 'vss', -1), ('IOVss', 'ring', 'MM', 'vdd', 1)]:
    extra.append(deck(cell, ctx, 'esd', st, ref, pol, opts=GEAR, suffix='_gear'))
open(os.path.join(DECKS, 'LIST_extra'), 'w').write('\n'.join(extra) + '\n')
print(len(names), 'decks')
