// Boîte noire de la macro csi2_top (ports seuls), livraison du prompt 060
(* blackbox *)
module csi2_top (
    input wire clk,
    input wire clk_w,
    input wire cnt_gel,
    output wire dbg_erreur,
    output wire dbg_evt,
    output wire fifo_tx_fin,
    input wire fifo_tx_full,
    output wire fifo_tx_wr,
    input wire rst_n,
    output wire rx_eol,
    output wire rx_pix_valid,
    output wire rx_short_ecc_corrected,
    output wire rx_short_sot_err,
    output wire rx_short_valid,
    output wire rx_sol,
    output wire rx_sol_ecc_corrected,
    output wire rx_sol_sot_err,
    output wire trame_fe,
    output wire trame_fe_ok,
    output wire trame_fs,
    output wire trame_late,
    output wire trame_slots_pleins,
    output wire tx_evt_nb,
    output wire tx_evt_width,
    output wire tx_init,
    output wire tx_init_done,
    output wire tx_pix_ready,
    input wire tx_pix_valid,
    output wire tx_req_ready,
    input wire tx_req_valid,
    output wire [3:0] dbg_verrou,
    input wire [3:0] enable,
    output wire [31:0] fifo_tx_wdata,
    output wire [3:0] fifo_tx_wlanes,
    input wire [3:0] hspr,
    output wire [15:0] llp_cnt_burst,
    output wire [15:0] llp_cnt_crc,
    output wire [15:0] llp_cnt_dt,
    output wire [15:0] llp_cnt_ecc_corrected,
    output wire [15:0] llp_cnt_ecc_double,
    output wire [15:0] llp_cnt_ok,
    output wire [15:0] llp_cnt_sot_err,
    output wire [15:0] llp_cnt_trunc,
    input wire [31:0] mots,
    input wire [1:0] renvoi_mode,
    output wire [2:0] rx_eol_status,
    output wire [83:0] rx_pix_data,
    output wire [2:0] rx_pix_nb,
    output wire [15:0] rx_short_data,
    output wire [5:0] rx_short_dt,
    output wire [1:0] rx_short_vc,
    output wire [5:0] rx_sol_dt,
    output wire [2:0] rx_sol_fmt,
    output wire [1:0] rx_sol_vc,
    output wire [15:0] rx_sol_wc,
    input wire [11:0] statut_phy,
    output wire [15:0] trame_cnt_err,
    output wire [15:0] trame_cnt_ligne,
    output wire [15:0] trame_cnt_ok,
    output wire [2:0] trame_err_end,
    output wire [1:0] trame_err_end_vc,
    output wire [6:0] trame_err_hdr,
    output wire [1:0] trame_err_hdr_vc,
    output wire [3:0] trame_late_mask,
    output wire [2:0] trame_loss,
    output wire [3:0] trame_loss_mask,
    output wire [15:0] trame_numero,
    output wire [1:0] trame_vc,
    input wire [111:0] tx_pix_data,
    input wire [3:0] tx_pix_nb,
    input wire [5:0] tx_req_dt,
    input wire [1:0] tx_req_vc,
    input wire [15:0] tx_req_width
);
endmodule
